### ISSUE TITLE
Error when making the payment 

### ISSUE THREAD

**Issue by jsramirezch** [Steffo99/greed#123]
```console
←[32m2021-05-06 16:43:41←[0m | Worker 1775961268 | ←[34mworker←[0m | ←[31mException in <Worker 1775961268>: 'order' is an invalid keyword argument for OrderItem←[0m
Traceback (most recent call last):
  File "C:\Users\jsram\greed\worker.py", line 211, in run
    self.__admin_menu()
  File "C:\Users\jsram\greed\worker.py", line 938, in __admin_menu
    self.__user_menu()
  File "C:\Users\jsram\greed\worker.py", line 472, in __user_menu
    self.__order_menu()
  File "C:\Users\jsram\greed\worker.py", line 654, in __order_menu
    order_item = db.OrderItem(product=cart[product][0],
  File "<string>", line 4, in __init__
  File "C:\Users\jsram\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\state.py", line 445, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\jsram\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\jsram\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\jsram\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\state.py", line 442, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\jsram\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1142, in _declarative_constructor
    raise TypeError(
TypeError: 'order' is an invalid keyword argument for OrderItem
```

**Comment by Steffo99** [comment]
Should be fixed in d3200b170a81b8a8d42ba36e82a7675621dd81e3 , please let me know!
