### ISSUE TITLE
Help! Bug - Add funds "Credit Card"

### ISSUE THREAD

**Issue by tripoflgb** [Steffo99/greed#135]
Hello, please help resolve this bug, example: view add funds 7$ (Min 10 - Max 100) 

Exception in <Worker 1091534037>: 'Credit Card'
Traceback (most recent call last):
  File "/srv/tlbot/worker.py", line 244, in run
    self.__admin_menu()
  File "/srv/tlbot/worker.py", line 1764, in __admin_menu
    self.__user_menu()
  File "/srv/tlbot/worker.py", line 680, in __user_menu
    self.__add_credit_menu()
  File "/srv/tlbot/worker.py", line 1582, in __add_credit_menu
    self.__add_credit_cc()
  File "/srv/tlbot/worker.py", line 1621, in __add_credit_cc
    min_amount=self.Price(self.cfg["Credit Card"]["min_amount"])))
  File "/srv/tlbot/nuconfig.py", line 15, in __getitem__
    return self.data.__getitem__(item)
KeyError: 'Credit Card'

**Comment by Steffo99** [comment]
Fixed.
