### ISSUE TITLE
Error add photo to product from Windows Telegram or Phone

### ISSUE THREAD

**Issue by tripoflgb** [Steffo99/greed#138]
Please help fix error, add proho to product from Windows Telegram client or phone (selected file)

Worker 1895432016 | worker | Exception in <Worker 1895432016>: list index out of range
Traceback (most recent call last):
  File "/root/garminbot/worker.py", line 254, in run
    self.__admin_menu()
  File "/root/garminbot/worker.py", line 1757, in __admin_menu
    self.__products_menu()
  File "/root/garminbot/worker.py", line 1966, in __products_menu
    self.__edit_product_menu()
  File "/root/garminbot/worker.py", line 2088, in __edit_product_menu
    largest_photo = photo_list[0]
IndexError: list index out of range

**Comment by Steffo99** [comment]
You sent a non-compressed photo, which greed doesn't support...

It's weird that python-telegram-bot considered it a photo, though...

I'll investigate when I have time.

**Comment by tripoflgb** [comment]
If i send a non-compressed / compressed photo, please fix in next update.

**Comment by Steffo99** [comment]
I think it's due to the [Bot API 5.3 update](https://core.telegram.org/bots/api#june-25-2021).

Now photos have a [different JSON structure](https://core.telegram.org/bots/api#chatphoto), so trying to access the `PhotoSize` array fails.

I think that something should be changed here:

https://github.com/Steffo99/greed/blob/28967de9fb26d7e0a01a4dd56a7e7e28fbae91ba/worker.py#L1067-L1070
