### ISSUE TITLE
Bug: Error sqlite3

### ISSUE THREAD

**Issue by tripoflgb** [Steffo99/greed#140]
Hello!
I receive this error in moment used your bot, please help fix.

**Please help fix - sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread**

**Comment by tripoflgb** [comment]
2021-06-16 14:17:46 | Worker 1619823728 | sqlalchemy.pool.impl.NullPool | Exception closing connection <sqlite3.Connection object at 0x7fb3f037a5d0>
Traceback (most recent call last):
  File "/root/tlbot/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/root/tlbot/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/root/tlbot/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140410795763456 and this is thread id 140410786846464.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tlbot/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 238, in _close_connection
    self._dialect.do_close(connection)
  File "/root/tlbot/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140410795763456 and this is thread id 140410786846464.

**Comment by Steffo99** [comment]
Can you please provide full logs? 

Set the

**Comment by Steffo99** [comment]
Can you please provide full logs?

https://github.com/Steffo99/greed/blob/28967de9fb26d7e0a01a4dd56a7e7e28fbae91ba/config/template_config.toml#L113

Set the logging level to `DEBUG`, then send me the full console output when the error occours.
