### ISSUE TITLE
Почему не работает?

### ISSUE THREAD

**Issue by kirillclone** [Steffo99/greed#155]
**Python 3.9** 

`2021-11-04 18:23:45 | Core | duckbot | Telegram error while calling get_updates(), retrying in 5 secs...

Full error: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
Traceback (most recent call last):
  File "C:\Users\kirillclon\PycharmProjects\greed55\duckbot.py",line 22, in result_func
    return func(*args, **kwargs)
  File "C:\Users\kirillclon\PycharmProjects\greed55\duckbot.py", line 82, in get_updates
    return self.bot.get_updates(*args, **kwargs)
  File "C:\Users\kirillclon\PycharmProjects\greed55\venv\lib\site-packages\telegram\bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\kirillclon\PycharmProjects\greed55\venv\lib\site-packages\telegram\bot.py", line 2761, in get_updates
    result = self._post(
  File "C:\Users\kirillclon\PycharmProjects\greed55\venv\lib\site-packages\telegram\bot.py", line 259, in _post
    return self.request.post(
  File "C:\Users\kirillclon\PycharmProjects\greed55\venv\lib\site-packages\telegram\utils\request.py", line 350, in post
    result = self._request_wrapper(
  File "C:\Users\kirillclon\PycharmProjects\greed55\venv\lib\site-packages\telegram\utils\request.py", line 277, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
`

**Comment by kirillclone** [comment]
Вопрос закрыт и ошибся в token

**Comment by Steffo99** [comment]
I... have no idea of what this issue means, but you seem to have resolved your problem.
