### ISSUE TITLE
error when i press /start

### ISSUE THREAD

**Issue by lobsik** [Steffo99/greed#46]
when i press start on bot i catching this error:

```
C:\tg_bot1\greed-master>python -OO core.py
greed-bot is now starting!
Traceback (most recent call last):
  File "core.py", line 131, in <module>
    main()
  File "core.py", line 63, in main
    new_worker = worker.ChatWorker(bot, update.message.chat)
  File "C:\tg_bot1\greed-master\worker.py", line 57, in __init__
    release=raven.fetch_git_sha(os.path.dirname(__file__)),
  File "D:\Python\lib\site-packages\raven\versioning.py", line 19, in fetch_git_
sha
    'Cannot identify HEAD for git repository at %s' % (path,))
raven.exceptions.InvalidGitRepository: Cannot identify HEAD for git repository a
t C:\tg_bot1\greed-master

C:\tg_bot1\greed-master>
```

**Comment by Steffo99** [comment]
This happens if you have Sentry configured but you downloaded `greed` from the zip file.

I'll fix this soon.

**Comment by Steffo99** [comment]
Fixed!
