### ISSUE TITLE
SQLite threading problems

### ISSUE THREAD

**Issue by Steffo99** [Steffo99/greed#53]
```
2020-04-29 01:02:53 | Worker 525147055 | sqlalchemy.pool.impl.NullPool | Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\pool\base.py", line 693, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\pool\base.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 540, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8780 and this is thread id 21508.
2020-04-29 01:02:53 | Worker 525147055 | sqlalchemy.pool.impl.NullPool | Exception closing connection <sqlite3.Connection object at 0x0000028D5F544D50>
Traceback (most recent call last):
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\pool\base.py", line 693, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\pool\base.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 540, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8780 and this is thread id 21508.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\pool\base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\stepi\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 546, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8780 and this is thread id 21508.
```

**Comment by Steffo99** [comment]
Seems to occour when too many things happen too fast...?
